### ISSUE TITLE
reformatar fundamento da questões de ética em YAML

### ISSUE THREAD

**Issue by pdelfino** [own-pt/oab-exams#39]
Construir um arquivo YAML com os dados da análise do fundamento das 30 questões de ética:

- [x] converter dados do arquivo justify.txt feito pelo Bruno para um novo em Yaml

- [x] transportar comentários do arquivo .tex com o fundamento de questões para  a seção de comentários do arquivo Yaml

**Comment by pdelfino** [comment]
Terminei de converter o arquivo do @odanoburu para yaml. Inseri os comentários que estavam no arquivo .tex.  @arademaker, vc poderia dar uma olhada na conversão e ver se tem algo ruim?

Por exemplo, algumas questões tinham como justificativa dois artigos e, as vezes, cada artigo tinha como justificativa um inciso. A forma que eu encontrei de lidar com isso foi, por exemplo:

```
-
  exam: 2015-18
  question: 4
  urn: urn:lex:br:federal:lei:1994-07-04;8906
  article: 9 28
  subsection: 9-third-paragraph 28-IV
comment: 
```

Seria interessante vc dar uma e ver se acha isso ou alguma outra coisa estranha.

**Comment by arademaker** [comment]
Acho que este issue é similar ao #51 , podiamos fechar um e continuar outro.

**Comment by pdelfino** [comment]
beleza

**Comment by arademaker** [comment]
BTW, acho que seu exemplo em https://github.com/own-pt/oab-exams/issues/39#issuecomment-354892412 não está bom, deveria ser algo como:

```
- exam: 2015-18
  question: 4
  urn: urn:lex:br:federal:lei:1994-07-04;8906
  article: [9, 28]
  subsection: 
  comment: No 9 terceiro parágrafo; no 28 item IV
```

Isto assumingo que não temos como codificar uma URI específica para o `artigo 9 terceiro parágrafo` e outra URI para `artigo 28 item IV`. Temos certo? E se as uris forem completas, sempre temos como decompor elas nos seus prefixos para obter o element principal.

**Comment by pdelfino** [comment]
Oi professor @arademaker ,

Só para deixar claro. Acho até que vc já percebeu com o comentário do @odanoburu, mas vou explicar de novo caso algo não tenha ficado claro.

A forma "correta", nesse momento, que estamos lidando com o arquivo yaml está expressa no arquivo do **justify-const!**

Vc mandou acima uma questão do **justify-ethics**! Ainda preciso consertar o justify-ethics com base no "avanço" que tivemos no justify-const. Esse avanço é recente, último sábado/domingo. Isso está, inclusive, anotado nessa issue https://github.com/own-pt/oab-exams/issues/56

A forma como resolvemos esse tipo de problema no justify-const e que, em breve, vou consertar no outro arquivo é usar a lista de yaml (sem ser com [], usando o outro approach):

```
- exam: 2012-08
  question: 13
  urn: urn:lex:br:federal:constituicao:1988-10-05;1988
  article: 
    - art95_cpt_inc2 
    - art98_cpt_inc8
  comment:  |
    A resposta está no 95-II, o ponto legal é que o próprio inciso II do
    95 cita o VIII do 98.
```
Nesse arquivo aqui tem inclusive um dicionário informal das convenções do LexML Brasil que eu considerei as mais importantes: https://github.com/own-pt/oab-exams/blob/master/justify/lexml-conventions.md
